### ISSUE TITLE
✨ [Feature] 모임 상세 페이지 UI 구현 - 이전 디자인

### ISSUE THREAD

**Issue by cloud0406** [codeit-team3/FE#55]
### 📄 설명

모임 상세 페이지의 레이아웃 및 ui를 구현 합니다.

**일반 유저**
![image](https://github.com/user-attachments/assets/30feeacf-5d4c-40a7-91fd-fb470f76d151)

**주최자**
![image](https://github.com/user-attachments/assets/daab3137-b3d2-43c6-974f-fce824d8cce7)

### ✅ 작업할 내용

- [ ] Ui 구현

**Comment by wynter24** [comment]
이전 디자인으로 구현된 페이지로 변경사항이 많아 사용할 수 없어 브랜치를 삭제하고 이슈를 닫습니다.
